jobs:
- job: BuildAndDeploy
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

- job: DeployToStaging
  dependsOn: BuildAndDeploy
  steps:
  - script: |
      echo "Deploying to Staging..."
      # Add deployment steps for staging environment
    displayName: 'Deploy to Staging'
